"""IItemRepository — structural Protocol (no concrete implementation here)."""
from __future__ import annotations

import uuid
from typing import Protocol

from app.domain.item.entity import Item


class IItemRepository(Protocol):
    async def add(self, item: Item) -> Item: ...
    async def get_by_id(self, item_id: uuid.UUID) -> Item | None: ...
    async def list_all(self, offset: int, limit: int) -> tuple[list[Item], int]: ...
    async def update(self, item: Item) -> Item: ...
    async def delete(self, item_id: uuid.UUID) -> None: ...
